/*
 * Copyright 2011 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.reporting;

import org.gradle.util.GradleVersion;

import java.text.DateFormat;
import java.util.Date;

public abstract class TabbedPageRenderer<T> extends AbstractHtmlReportRenderer<T> {
    private T model;

    protected T getModel() {
        return model;
    }

    protected abstract String getTitle();

    protected abstract AbstractHtmlReportRenderer<T> getHeaderRenderer();

    protected abstract AbstractHtmlReportRenderer<T> getContentRenderer();

    protected String getPageTitle() {
        return getTitle();
    }

    @Override
    public void render(T model, HtmlBuilder html) {
        this.model = model;
        html.head();
            html.meta().httpEquiv("Content-Type").content("text/html; charset=utf-8");
            html.title().text(getTitle()).end();
            html.link().rel("stylesheet").type("text/css").href("base-style.css");
            html.link().rel("stylesheet").type("text/css").href("style.css");
            html.script().src("report.js").type("text/javascript").end();
        html.end();

        // <body>
        html.body();

        // Content
            html.div().attr("id", "content");
            html.h1().text(getPageTitle()).end();

            getHeaderRenderer().render(model, html);
            getContentRenderer().render(model, html);

            // Footer
            html.div().id("footer");
                html.p().text("Generated by ");
                    html.a().href("http://www.gradle.org").text(String.format("Gradle %s", GradleVersion.current().getVersion())).end();
                    html.text(String.format(" at %s", DateFormat.getDateTimeInstance().format(new Date())));
                html.end();
            html.end();
        html.end();
    }
}
